# This file must be kept in sync with .gorleaser.yaml except for release section
# yaml-language-server: $schema=https://raw.githubusercontent.com/goreleaser/goreleaser/v2.13.2/www/docs/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

project_name: gitops-promoter
version: 2

dist: release_dist

before:
  hooks:
    - go mod tidy
    - go mod download
    - make build-dashboard # Builds the dashboards UI and embeds it
    - make build-extension # Build the ArgoCD extension

builds:
  - id: gitops-promoter
    main: ./cmd
    binary: gitops-promoter
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -v
    goos:
      - linux
    ldflags:
      - -X github.com/argoproj-labs/gitops-promoter/common.version=latest
      - -X github.com/argoproj-labs/gitops-promoter/common.buildDate={{ .Date }}
      - -extldflags="-static"

dockers:
  - image_templates:
      - quay.io/argoprojlabs/gitops-promoter:latest-amd64
    dockerfile: release.Dockerfile
    use: buildx
    goarch: amd64
    extra_files:
      - hack/git/promoter_askpass.sh
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version=latest"
      - "--platform=linux/amd64"
  - image_templates:
      - quay.io/argoprojlabs/gitops-promoter:latest-arm64
    dockerfile: release.Dockerfile
    use: buildx
    goarch: arm64
    extra_files:
      - hack/git/promoter_askpass.sh
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version=latest"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "quay.io/argoprojlabs/gitops-promoter:latest"
    image_templates:
      - "quay.io/argoprojlabs/gitops-promoter:latest-amd64"
      - "quay.io/argoprojlabs/gitops-promoter:latest-arm64"

# No archives for latest builds
archives:
  - id: binary
    formats: [tar.gz]
    ids:
      - "gitops-promoter"
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
  - id: extension
    name_template: "{{ .ProjectName }}-argocd-extension"
    formats: [tar.gz]
    meta: true
    files:
      - ui/extension/dist/extension-promoter.js
    # Wrap in top-level resources directory to be compatible with the extension installer: https://github.com/argoproj-labs/argocd-extension-installer/blob/4684a5d2fb8b94269ee22556794aad229485f48d/README.md#L25
    wrap_in_directory: 'resources'

# No GitHub release for latest builds
release:
  disable: true

# No changelog needed
changelog:
  disable: true
